version:  '3.5'

volumes:
  postgre-vol:

networks:
  kube-news-net:
    driver: bridge

services:
  web:
    image: zxdoc/kube-news:v1
    ports:
    - 8080:8080
    networks:
      - kube-news-net
    depends_on:
      - postgre
    environment:
      DB_DATABASE: kubenews
      DB_USERNAME: kubenews
      DB_PASSWORD: pg123
      DB_HOST: postgre

  postgre:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - kube-news-net  
    volumes:
      - postgre-vol:/var/lib/postgresql/data
  
    environment:
      POSTGRES_PASSWORD:  pg123
      POSTGRES_USER:  kubenews
      POSTGRES_DB:  kubenews